version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
    volumes:
      - ./services/nginx/conf.d/${ENV}:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx
      - ${SSL_PATH}:/etc/nginx/ssl
    networks:
      - docker_network
    depends_on:
      - kirin-bear-web
      - kirin-bear-api

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    expose:
      - "3000"
    volumes:
      - ./services/grafana/data:/var/lib/grafana
    networks:
      - docker_network

  mysql:
    container_name: mysql
    image: mysql:8.0.31
    # слушаешь извне
    ports:
      - "3306:3306"
    # для других контейнеров
    expose:
      - "3306"
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # TODO: правильнее сделать через отдельный volume
      - ./services/mysql/lib:/var/lib/mysql
    networks:
      - docker_network

  minio:
    container_name: minio
    image: minio/minio
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./services/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address=":9001" /data
    networks:
      - docker_network

  kirin-bear-api:
    container_name: kirin-bear-api
    build:
      context: ${KIRIN_BEAR_API_PATH}/
      dockerfile: Dockerfile
      target: ${ENV}
    networks:
      - docker_network

  kirin-bear-web:
    container_name: kirin-bear-web
    build:
      context: ${KIRIN_BEAR_WEB_PATH}/
      dockerfile: Dockerfile
      target: ${ENV}
    networks:
      - docker_network

networks:
  docker_network:
    ipam:
      driver: default