version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx
    networks:
      - server_docker_network
    depends_on:
      - kirin-bear-web
      - kirin-bear-api

  kirin-bear-api:
    container_name: kirin-bear-api
    build:
      context: ${KIRIN_BEAR_API_PATH}/
      target: ${ENV}
      dockerfile: Dockerfile
    volumes:
      - ${KIRIN_BEAR_API_PATH}:/var/www
    networks:
      - server_docker_network

  kirin-bear-web:
    container_name: kirin-bear-web
    build:
      context: ${KIRIN_BEAR_WEB_PATH}/
      dockerfile: Dockerfile
    networks:
      - server_docker_network


networks:
  server_docker_network:
    ipam:
      driver: default