services:
  kirin-bear-web:
    volumes:
      # для xmr пришлось вынести сюда - надо переделать на docker-compose.override.yml
      # чтобы на проде не было ненужных volumes, так как там используется только конечный набор статики
      - ${KIRIN_BEAR_WEB_PATH}/src:/home/node/app/src:rw