# config для local --------------------------
server {
    listen 80;
    server_name kirin-bear-grafana.localhost;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://grafana:3000;
    }
}