server {

    include mime.types;
    sendfile on;

    listen 80;
    server_name kirin-bear.site *.kirin-bear.site kirin-bear.online *.kirin-bear.online;
    client_max_body_size 100m;

    location / {
        default_type text/html;
        return 200 "by kirin a.p.";
    }
}