server {
    listen 80;
    server_name api.kirin-bear.ru;
    return 301 https://$host$request_uri;
}

server {
    include mime.types;
    sendfile on;

    add_header Access-Control-Allow-Origin "kirin-bear.ru";

    listen 443 ssl;
    server_name api.kirin-bear.ru;
    client_max_body_size 100m;

    ssl_certificate /etc/nginx/ssl/kirin-bear.ru/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/kirin-bear.ru/kirin-bear.ru.key;

    # необходим резолвер для докер контейнера
    ssl_stapling on;
    resolver 127.0.0.11 ipv6=off valid=300s;
    ssl_stapling_verify on;

    # скажем запомнить браузеру обращаться по https на 1 год, чтобы не редиректить все время
    # add_header Strict-Transport-Security 'max-age=31536000';
    # add_header Content-Security-Policy 'block-all-mixed-conten';

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $remote_addr;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://kirin-bear-api:8080;
    }
}