server {
    listen 80;
    server_name rabbitmq.kirin-bear.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rabbitmq.kirin-bear.ru;

    ssl_certificate /etc/nginx/ssl/kirin-bear.ru/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/kirin-bear.ru/kirin-bear.ru.key;

    # необходим резолвер для докер контейнера
    ssl_stapling on;
    resolver 127.0.0.11 ipv6=off valid=300s;
    ssl_stapling_verify on;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://rabbitmq:15672;
    }
}
