server {
    listen 8081;
    server_name rabbitmq.kirin-bear.ru;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://rabbitmq:15672;
    }
}
