server {

    include mime.types;
    sendfile on;

    listen 80;

    client_max_body_size 100m;

    location / {
        proxy_pass http://kirin-bear-web:8080;
    }

    location /me {
        default_type text/html;
        return 200 "hello!";
    }
}