# config для local --------------------------
server {

    include mime.types;
    sendfile on;

    listen 80;
    server_name kirin-bear-api.localhost;
    client_max_body_size 100m;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $remote_addr;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://kirin-bear-api:8080;
    }

    location /me {
        default_type text/html;
        return 200 "api.kirin-bear.ru";
    }
}

# config для prod ----------------------------
server {
    listen 80;
    server_name api.kirin-bear.ru;
    rewrite ^(.*) https://api.kirin-bear.ru$1 permanent;
}

server {
    include mime.types;
    sendfile on;

    listen 443 ssl;
    server_name api.kirin-bear.ru;
    client_max_body_size 100m;

    ssl_certificate /home/develop/.acme.sh/kirin-bear.ru/fullchain.cer
    ssl_certificate_key /home/develop/.acme.sh/kirin-bear.ru/kirin-bear.ru.key

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $remote_addr;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://kirin-bear-api:8080;
    }
}